services:
  discordbot:
    image: ghcr.io/hoppipo/hoppipotame-discord:main
    container_name: DiscordBot
    restart: unless-stopped
    environment:
      HOPPIPOTAME_DISCORD_TOKEN: ${HOPPIPOTAME_DISCORD_TOKEN}
      TMDB_JWT: ${TMDB_JWT}
