services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /home/plex/library:/config
      - /home/plex/movies:/movies
    restart: unless-stopped
