services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Paris
      - PLEX_CLAIM=${PLEX_CLAIM}
    hostname: Plex Hoppipotame
    volumes:
      - /home/plex/config:/config
      - /home/plex/transcode:/transcode
      - /home/plex/media:/data
    devices:
      - /dev/dri:/dev/dri
