services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    volumes:
      - /home/plex/library:/config
      - /home/plex/movies:/movies
    restart: unless-stopped
