services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    ports:
      – 32400:32400/tcp
      – 3005:3005/tcp
      – 8324:8324/tcp
      – 32469:32469/tcp
      – 1900:1900/udp
      – 32410:32410/udp
      – 32412:32412/udp
      – 32413:32413/udp
      – 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    volumes:
      - /home/plex/library:/config
      - /home/plex/movies:/movies
    restart: unless-stopped
