services:
  qbittorrent-nox:
    container_name: qbittorrent-nox
    environment:
      - QBT_EULA=${QBT_EULA}
      - QBT_VERSION=${QBT_VERSION}
      - QBT_WEBUI_PORT=${QBT_WEBUI_PORT}
    image: qbittorrentofficial/qbittorrent-nox:${QBT_VERSION}
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - ${QBT_WEBUI_PORT}:${QBT_WEBUI_PORT}/tcp
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    restart: unless-stopped
    tty: true
    volumes:
      - ${QBT_CONFIG_PATH}:/config
      - ${QBT_DOWNLOADS_PATH}:/downloads
      - ${QBT_TEMP_PATH}:/temp
      - ${QBT_TORRENT_PATH}/downloading:/torrent/downloading
      - ${QBT_TORRENT_PATH}/finished:/torrent/finished
      - ${QBT_TORRENT_PATH}/waiting:/torrent/waiting